sudo:     false
language: ruby
before_install:
  #
  # bundler 2.0.1 requires Ruby version >= 2.3.0 but we still want to
  # support back to 2.2.2.
  #
  - gem install bundler -v 1.17.1
services:
  - redis-server
rvm:
  - 2.1.10
  - 2.2.2
  - 2.2.10
  - 2.3.7
  - 2.4.6
  - 2.5.5
  - 2.6.3
gemfile:
  - gemfiles/redis_3.0.gemfile
  - gemfiles/redis_3.1.gemfile
  - gemfiles/redis_3.2.gemfile
  - gemfiles/redis_3.3.gemfile
  - gemfiles/redis_4.0.gemfile
  - gemfiles/redis_4.1.gemfile
script:
  - bundle exec rubocop --display-cop-names --display-style-guide
  - bundle exec env REDIS_URL=redis://localhost:6379 rake test
